#!/usr/bin/env python3
# This file is placed in the Public Domain.


"build"


import os


def popen(txt):
    "run command"
    for line in os.popen(txt).readlines():
        print(line.strip())


popen("python3 setup.py sdist bdist_wheel")
