#!/usr/bin/env python3
# This file is placed in the Public Domain.


"check"


import os


from skip import popen


ALL = [
       "__import__\(",
       "__main__",
       "__version__",
       '"## "',
       "popen\(",
       "pkgutil",
       "importlib",
       "print\("
      ]


SKIP = [
        ".git",
        "bin",
        "fin",
        "docs",
        "env",
        "README",
        "zcmd"
       ]


def doskip(txt, skiplist=[]):
    for skip in skiplist:
        if skip in txt:
            return True
    return False


def popen(txt):
    for line in os.popen(txt).readlines():
        if doskip(line, SKIP):
            continue
        print(line.strip())


for txt in ALL:
    popen("grep -R %s" % txt)
