#!/usr/bin/env python3
# This file is placed in the Public Domain.


"cleanup"


from skip import popen


popen("bin/clean")
popen("rm -fR fin/*~")
popen("fin/loop . rm -fRv \*~")
popen("fin/loop . rm -fR __pycache__")
