#!/usr/bin/env python3
# This file is placed in the Public Domain.


"cleanup"


from skip import popen


popen("rm -fRv build dist MANIFEST *.egg-info")
popen("rm -fv *~")
popen("rm -fRv .test .pytest_cache")
popen("rm -fRv html docs/operbot*.rst docs/op*.rst")
popen("fin/loop . rm -fRv \*~")
popen("fin/loop . rm -fRv __pycache__")
