#!/usr/bin/env python3
# This file is placed in the Public Domain.


"lint"


import os
import skip
import sys


from skip import SKIP, doskip, popen


try:
    SKIP = [x.strip() for x in open("fin/skip.cfg", "r").read().split(",")]
    print(SKIP)
except:
    pass


def loop(path, txt):
    for tdo in os.listdir(path):
        if not os.path.isdir(tdo):
            continue
        if doskip(tdo):
            continue
        ppp = os.path.join(path, tdo)
        print("linting %s" % ppp)
        os.chdir(ppp)
        #for fnm in os.listdir(ppp):
        sys.stdout.flush()
        popen(txt)
        sys.stdout.flush()
        os.chdir("..")


if __name__ == "__main__":
    loop(os.getcwd(), "pylint *")
