#!/usr/bin/env python3
# This file is placed in the Public Domain.


"lint"


import os
import skip
import sys


from skip import popen


skip.SKIP = ["---", "Your code"]


def loop(path, txt):
    for fnn in os.listdir(path):
        if not os.path.isdir(fnn):
            continue
        if not os.path.exists("%s/__init__.py" % fnn):
            continue
        os.chdir(fnn)
        popen(txt)
        sys.stdout.flush()
        os.chdir("..")


if __name__ == "__main__":
    loop(os.getcwd(), "pylint *")
