#!/usr/bin/env python3
# This file is placed in the Public Domain


"build all"


import os


SILENT = 1


def popen(txt):
    for line in os.popen(txt).readlines():
        if not SILENT:
            print(line.rstrip())


popen("bins/wipe")
popen("bins/check")
popen("bins/build")
popen("bins/lint")
popen("bins/test")
popen("bins/tinder")
popen("bins/env")
