#!/usr/bin/env python3
# This file is placed in the Public Domain.


"build"


import os
import sys


sys.path.insert(0, os.getcwd())


TODO = ["op", "operbot"]


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())


popen("rm -fR ~/.cache/pip")
popen("rm -fR tar")
popen("mkdir tar")

for td in TODO:
    print("## processing %s" % td)
    os.chdir("src/%s" % td)
    popen("bin/clean")
    popen("python3 setup.py sdist")
    popen("cp dist/* ../../tar/")
    os.chdir("..")
    os.chdir("..")
