#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os


ALL = [
       "__import__",
       "__main__",
       "__version__",
       '"## "',
       "popen\(",
       "pkgutil",
       "importlib",
       "print\(",
       "sys",
      ]


SKIP = [
        ".git",
        "README",
        "bin",
        "docs",
        "grep",
        "test"
       ]


TXT  = "grep -R %s"


def main():
    for txt in ALL:
        greptxt = TXT % txt
        for line in os.popen(greptxt).readlines():
            donext = False
            for skip in SKIP:
                if skip in line:
                    donext = True
                    break
            if donext:
                continue
            print(line.rstrip())


main()
