#!/usr/bin/env python3
# This file is placed in the Public Domain.


"cleanup"


import os


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line)


popen("rm -fR build dist MANIFEST *~ .op operbot.egg-info __pycache__ .pytest_cache")
popen("rm -fR op/*~ op/__pycache__")
popen("rm -fR oper/*~ oper/__pycache__")
popen("rm -fR operbot/*~ operbot/__pycache__")
popen("rm -fR bin/*~ bin/__pycache__")
popen("rm -fR .test test/__pycache__ test/*~")
popen("rm -fR docs/_static/*~ docs/_templates/*~ docs/*~ docs/bot*.rst docs/run*.rst docs/opl*.rst docs/op*.rst docs/operbot*.rst")
