#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


sys.path.insert(0, os.getcwd())


TODO = ["op", "operbot"]

def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())


popen("rm -fR env")
popen("rm -fR tar")
popen('mkdir tar')
popen("rm -fR src")
popen("mkdir src")


for td in TODO:
    print("cloning %s" % td)
    popen("git clone ssh://git@github.com/operbot/%s src/%s/" % (td, td))
